version: '2'
services:
  scheduler:
    image: spiside/luigi:latest
    ports:
      - "8082:8082"
    environment:
      LUIGI_TASK_HISTORY_DB_CONNECTION: postgres://luigi@db/dev
      LUIGI_SCHEDULER_RECORD_TASK_HISTORY: "true"
    depends_on:
      - db
    entrypoint:
      - ./wait-for-postgres.sh
      - db
  db:
    image: postgres:9.5.4
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: luigi
      POSTGRES_DB: dev
